//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.ApplicationData>
    {
    
        public ApplicationDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).ApplicationData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.ApplicationData>
    {
        public ApplicationDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Course> MyCourses()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Course> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.Course>("Courses");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeTrainingRecord> MyTrainingRecords()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.EmployeeTrainingRecord> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.EmployeeTrainingRecord>("EmployeeTrainingRecords");
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.Course))
            {
                return new global::LightSwitchApplication.Implementation.Course();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.CourseStatus))
            {
                return new global::LightSwitchApplication.Implementation.CourseStatus();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.EmployeeCourseAssignment))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeCourseAssignment();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.EmployeeGroupCourseAssignment))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeGroupCourseAssignment();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.EmployeeGroup))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeGroup();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.EmployeeJobRole))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeJobRole();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.EmployeeTrainingRecord))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeTrainingRecord();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.JobRoleCourseAssignment))
            {
                return new global::LightSwitchApplication.Implementation.JobRoleCourseAssignment();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.JobRole))
            {
                return new global::LightSwitchApplication.Implementation.JobRole();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TrainingSessionAttendee))
            {
                return new global::LightSwitchApplication.Implementation.TrainingSessionAttendee();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TrainingSession))
            {
                return new global::LightSwitchApplication.Implementation.TrainingSession();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.ApplicationData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.ApplicationData(this.GetEntityConnectionString(
                "_IntrinsicData",
                "res://" + assemblyName + "/ApplicationData.csdl|res://" + assemblyName + "/ApplicationData.ssdl|res://" + assemblyName + "/ApplicationData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Course))
            {
                return new global::LightSwitchApplication.Implementation.Course();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.CourseStatus))
            {
                return new global::LightSwitchApplication.Implementation.CourseStatus();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeCourseAssignment))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeCourseAssignment();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeGroupCourseAssignment))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeGroupCourseAssignment();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeGroup))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeGroup();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeJobRole))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeJobRole();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeTrainingRecord))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeTrainingRecord();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.JobRoleCourseAssignment))
            {
                return new global::LightSwitchApplication.Implementation.JobRoleCourseAssignment();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.JobRole))
            {
                return new global::LightSwitchApplication.Implementation.JobRole();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TrainingSessionAttendee))
            {
                return new global::LightSwitchApplication.Implementation.TrainingSessionAttendee();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TrainingSession))
            {
                return new global::LightSwitchApplication.Implementation.TrainingSession();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.ApplicationDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Course) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Course);
            }
            if (typeof(global::LightSwitchApplication.CourseStatus) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.CourseStatus);
            }
            if (typeof(global::LightSwitchApplication.EmployeeCourseAssignment) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeCourseAssignment);
            }
            if (typeof(global::LightSwitchApplication.EmployeeGroupCourseAssignment) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeGroupCourseAssignment);
            }
            if (typeof(global::LightSwitchApplication.EmployeeGroup) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeGroup);
            }
            if (typeof(global::LightSwitchApplication.EmployeeJobRole) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeJobRole);
            }
            if (typeof(global::LightSwitchApplication.Employee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Employee);
            }
            if (typeof(global::LightSwitchApplication.EmployeeTrainingRecord) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeTrainingRecord);
            }
            if (typeof(global::LightSwitchApplication.JobRoleCourseAssignment) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.JobRoleCourseAssignment);
            }
            if (typeof(global::LightSwitchApplication.JobRole) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.JobRole);
            }
            if (typeof(global::LightSwitchApplication.TrainingSessionAttendee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TrainingSessionAttendee);
            }
            if (typeof(global::LightSwitchApplication.TrainingSession) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TrainingSession);
            }
            return null;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Course :
        global::LightSwitchApplication.Course.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Course.DetailsClass.IImplementation.CourseStatus
        {
            get
            {
                return this.CourseStatus;
            }
            set
            {
                this.CourseStatus = (global::LightSwitchApplication.Implementation.CourseStatus)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("CourseStatus");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Course.DetailsClass.IImplementation.EmployeeGroupCourseAssignments
        {
            get
            {
                return this.EmployeeGroupCourseAssignments;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Course.DetailsClass.IImplementation.EmployeeCourseAssignments
        {
            get
            {
                return this.EmployeeCourseAssignments;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Course.DetailsClass.IImplementation.JobRoleCourseAssignments
        {
            get
            {
                return this.JobRoleCourseAssignments;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Course.DetailsClass.IImplementation.EmployeeTrainingRecords
        {
            get
            {
                return this.EmployeeTrainingRecords;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Course.DetailsClass.IImplementation.TrainingSessions
        {
            get
            {
                return this.TrainingSessions;
            }
        }
        
        partial void OnCourseStatus_CourseChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("CourseStatus");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class CourseStatus :
        global::LightSwitchApplication.CourseStatus.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.CourseStatus.DetailsClass.IImplementation.Courses
        {
            get
            {
                return this.Courses;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeCourseAssignment :
        global::LightSwitchApplication.EmployeeCourseAssignment.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeCourseAssignment.DetailsClass.IImplementation.Course
        {
            get
            {
                return this.Course;
            }
            set
            {
                this.Course = (global::LightSwitchApplication.Implementation.Course)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Course");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeCourseAssignment.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Employee");
                }
            }
        }
        
        partial void OnEmployeeCourseAssignment_CourseChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Course");
            }
        }
        
        partial void OnEmployeeCourseAssignment_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Employee");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeGroupCourseAssignment :
        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.IImplementation.EmployeeGroup
        {
            get
            {
                return this.EmployeeGroup;
            }
            set
            {
                this.EmployeeGroup = (global::LightSwitchApplication.Implementation.EmployeeGroup)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("EmployeeGroup");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.IImplementation.Course
        {
            get
            {
                return this.Course;
            }
            set
            {
                this.Course = (global::LightSwitchApplication.Implementation.Course)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Course");
                }
            }
        }
        
        partial void OnEmployeeGroupCourseAssignment_EmployeeGroupChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("EmployeeGroup");
            }
        }
        
        partial void OnEmployeeGroupCourseAssignment_CourseChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Course");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeGroup :
        global::LightSwitchApplication.EmployeeGroup.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.EmployeeGroup.DetailsClass.IImplementation.Employees
        {
            get
            {
                return this.Employees;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.EmployeeGroup.DetailsClass.IImplementation.EmployeeGroupCourseAssignments
        {
            get
            {
                return this.EmployeeGroupCourseAssignments;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeJobRole :
        global::LightSwitchApplication.EmployeeJobRole.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeJobRole.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Employee");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeJobRole.DetailsClass.IImplementation.JobRole
        {
            get
            {
                return this.JobRole;
            }
            set
            {
                this.JobRole = (global::LightSwitchApplication.Implementation.JobRole)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("JobRole");
                }
            }
        }
        
        partial void OnEmployeeJobRole_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Employee");
            }
        }
        
        partial void OnEmployeeJobRole_JobRoleChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("JobRole");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Employee :
        global::LightSwitchApplication.Employee.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Employee.DetailsClass.IImplementation.EmployeeGroup
        {
            get
            {
                return this.EmployeeGroup;
            }
            set
            {
                this.EmployeeGroup = (global::LightSwitchApplication.Implementation.EmployeeGroup)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("EmployeeGroup");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.EmployeeCourseAssignments
        {
            get
            {
                return this.EmployeeCourseAssignments;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.EmployeeJobRoles
        {
            get
            {
                return this.EmployeeJobRoles;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.EmployeeTrainingRecords
        {
            get
            {
                return this.EmployeeTrainingRecords;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.TrainingSessions
        {
            get
            {
                return this.TrainingSessions;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.TrainingSessionAttendees
        {
            get
            {
                return this.TrainingSessionAttendees;
            }
        }
        
        partial void OnEmployeeGroup_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("EmployeeGroup");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeTrainingRecord :
        global::LightSwitchApplication.EmployeeTrainingRecord.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeTrainingRecord.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Employee");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeTrainingRecord.DetailsClass.IImplementation.Course
        {
            get
            {
                return this.Course;
            }
            set
            {
                this.Course = (global::LightSwitchApplication.Implementation.Course)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Course");
                }
            }
        }
        
        partial void OnEmployeeTrainingRecord_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Employee");
            }
        }
        
        partial void OnEmployeeTrainingRecord_CourseChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Course");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class JobRoleCourseAssignment :
        global::LightSwitchApplication.JobRoleCourseAssignment.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.JobRoleCourseAssignment.DetailsClass.IImplementation.JobRole
        {
            get
            {
                return this.JobRole;
            }
            set
            {
                this.JobRole = (global::LightSwitchApplication.Implementation.JobRole)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("JobRole");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.JobRoleCourseAssignment.DetailsClass.IImplementation.Course
        {
            get
            {
                return this.Course;
            }
            set
            {
                this.Course = (global::LightSwitchApplication.Implementation.Course)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Course");
                }
            }
        }
        
        partial void OnJobRoleCourseAssignment_JobRoleChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("JobRole");
            }
        }
        
        partial void OnJobRoleCourseAssignment_CourseChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Course");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class JobRole :
        global::LightSwitchApplication.JobRole.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.JobRole.DetailsClass.IImplementation.EmployeeJobRoles
        {
            get
            {
                return this.EmployeeJobRoles;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.JobRole.DetailsClass.IImplementation.JobRoleCourseAssignments
        {
            get
            {
                return this.JobRoleCourseAssignments;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TrainingSessionAttendee :
        global::LightSwitchApplication.TrainingSessionAttendee.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TrainingSessionAttendee.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Employee");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TrainingSessionAttendee.DetailsClass.IImplementation.TrainingSession
        {
            get
            {
                return this.TrainingSession;
            }
            set
            {
                this.TrainingSession = (global::LightSwitchApplication.Implementation.TrainingSession)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("TrainingSession");
                }
            }
        }
        
        partial void OnTrainingSessionAttendee_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Employee");
            }
        }
        
        partial void OnTrainingSessionAttendee_TrainingSessionChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("TrainingSession");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TrainingSession :
        global::LightSwitchApplication.TrainingSession.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TrainingSession.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Employee");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TrainingSession.DetailsClass.IImplementation.Course
        {
            get
            {
                return this.Course;
            }
            set
            {
                this.Course = (global::LightSwitchApplication.Implementation.Course)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Course");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.TrainingSession.DetailsClass.IImplementation.TrainingSessionAttendees
        {
            get
            {
                return this.TrainingSessionAttendees;
            }
        }
        
        partial void OnTrainingSession_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Employee");
            }
        }
        
        partial void OnTrainingSession_CourseChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Course");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

