

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class EmployeeGroup : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the EmployeeGroup entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EmployeeGroup()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EmployeeGroup(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EmployeeGroup> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.EmployeeGroup.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmployeeGroup_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmployeeGroup_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroup.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.EmployeeGroup.DetailsClass.SetValue(this, global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string EmployeeGroupName
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroup.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.EmployeeGroupName);
            }
            set
            {
                global::LightSwitchApplication.EmployeeGroup.DetailsClass.SetValue(this, global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.EmployeeGroupName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmployeeGroupName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmployeeGroupName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmployeeGroupName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroup.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo CreatedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.CreatedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroup.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroup.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo ModifiedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.ModifiedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroup.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroup.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.EmployeeGroup.DetailsClass.SetValue(this, global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Employee> Employees
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroup.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.Employees);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Employee> EmployeesQuery
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroup.DetailsClass.GetQuery(this, global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.Employees);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.EmployeeGroupCourseAssignment> EmployeeGroupCourseAssignments
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroup.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.EmployeeGroupCourseAssignments);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.EmployeeGroupCourseAssignment> EmployeeGroupCourseAssignmentsQuery
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroup.DetailsClass.GetQuery(this, global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.EmployeeGroupCourseAssignments);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.EmployeeGroup,
                global::LightSwitchApplication.EmployeeGroup.DetailsClass,
                global::LightSwitchApplication.EmployeeGroup.DetailsClass.IImplementation,
                global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass>.Entry
                __EmployeeGroupEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass>.Entry(
                    global::LightSwitchApplication.EmployeeGroup.DetailsClass.__EmployeeGroup_CreateNew,
                    global::LightSwitchApplication.EmployeeGroup.DetailsClass.__EmployeeGroup_Created,
                    global::LightSwitchApplication.EmployeeGroup.DetailsClass.__EmployeeGroup_AllowSaveWithErrors);
            private static global::LightSwitchApplication.EmployeeGroup __EmployeeGroup_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EmployeeGroup> es)
            {
                return new global::LightSwitchApplication.EmployeeGroup(es);
            }
            private static void __EmployeeGroup_Created(global::LightSwitchApplication.EmployeeGroup e)
            {
                e.EmployeeGroup_Created();
            }
            private static bool __EmployeeGroup_AllowSaveWithErrors(global::LightSwitchApplication.EmployeeGroup e)
            {
                bool result = false;
                e.EmployeeGroup_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string> EmployeeGroupName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.EmployeeGroupName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::LightSwitchApplication.Employee> Employees
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.Employees) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::LightSwitchApplication.Employee>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::LightSwitchApplication.EmployeeGroupCourseAssignment> EmployeeGroupCourseAssignments
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.EmployeeGroupCourseAssignments) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::LightSwitchApplication.EmployeeGroupCourseAssignment>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string EmployeeGroupName { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::System.Collections.IEnumerable Employees { get; }
                new global::System.Collections.IEnumerable EmployeeGroupCourseAssignments { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, int>.Data> c, global::LightSwitchApplication.EmployeeGroup.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeGroup e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.EmployeeGroup e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.EmployeeGroup.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.EmployeeGroup.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.EmployeeGroup e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string>.Entry
                    EmployeeGroupName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string>.Entry(
                        "EmployeeGroupName",
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._EmployeeGroupName_Stub,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._EmployeeGroupName_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._EmployeeGroupName_Validate,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._EmployeeGroupName_GetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._EmployeeGroupName_SetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._EmployeeGroupName_OnValueChanged);
                private static void _EmployeeGroupName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string>.Data> c, global::LightSwitchApplication.EmployeeGroup.DetailsClass d, object sf)
                {
                    c(d, ref d._EmployeeGroupName, sf);
                }
                private static bool _EmployeeGroupName_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeGroup e)
                {
                    bool result = false;
                    e.EmployeeGroupName_IsReadOnly(ref result);
                    return result;
                }
                private static void _EmployeeGroupName_Validate(global::LightSwitchApplication.EmployeeGroup e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EmployeeGroupName_Validate(r);
                }
                private static string _EmployeeGroupName_GetImplementationValue(global::LightSwitchApplication.EmployeeGroup.DetailsClass d)
                {
                    return d.ImplementationEntity.EmployeeGroupName;
                }
                private static void _EmployeeGroupName_SetImplementationValue(global::LightSwitchApplication.EmployeeGroup.DetailsClass d, string v)
                {
                    d.ImplementationEntity.EmployeeGroupName = v;
                }
                private static void _EmployeeGroupName_OnValueChanged(global::LightSwitchApplication.EmployeeGroup e)
                {
                    e.EmployeeGroupName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string>.Data> c, global::LightSwitchApplication.EmployeeGroup.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeGroup e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.EmployeeGroup e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.EmployeeGroup.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.EmployeeGroup e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.EmployeeGroup.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeGroup e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.EmployeeGroup e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.EmployeeGroup.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.EmployeeGroup e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string>.Data> c, global::LightSwitchApplication.EmployeeGroup.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeGroup e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.EmployeeGroup e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.EmployeeGroup.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.EmployeeGroup e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.EmployeeGroup.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeGroup e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.EmployeeGroup e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.EmployeeGroup.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.EmployeeGroup e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.EmployeeGroup.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeGroup e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.EmployeeGroup e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.EmployeeGroup.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.EmployeeGroup.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.EmployeeGroup e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::LightSwitchApplication.Employee>.Entry
                    Employees = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::LightSwitchApplication.Employee>.Entry(
                        "Employees",
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Employees_Stub,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Employees_GetReferencedEntities,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._Employees_GetEntityCollection);
                private static void _Employees_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::LightSwitchApplication.Employee>.Data> c, global::LightSwitchApplication.EmployeeGroup.DetailsClass d, object sf)
                {
                    c(d, ref d._Employees, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Employee> _Employees_GetReferencedEntities(global::LightSwitchApplication.EmployeeGroup.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Employee, global::LightSwitchApplication.Employee.DetailsClass>(global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.Employees, ref d._Employees);
                }
                private static global::System.Collections.IEnumerable _Employees_GetEntityCollection(global::LightSwitchApplication.EmployeeGroup.DetailsClass d)
                {
                    return d.ImplementationEntity.Employees;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::LightSwitchApplication.EmployeeGroupCourseAssignment>.Entry
                    EmployeeGroupCourseAssignments = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::LightSwitchApplication.EmployeeGroupCourseAssignment>.Entry(
                        "EmployeeGroupCourseAssignments",
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._EmployeeGroupCourseAssignments_Stub,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._EmployeeGroupCourseAssignments_GetReferencedEntities,
                        global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties._EmployeeGroupCourseAssignments_GetEntityCollection);
                private static void _EmployeeGroupCourseAssignments_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::LightSwitchApplication.EmployeeGroupCourseAssignment>.Data> c, global::LightSwitchApplication.EmployeeGroup.DetailsClass d, object sf)
                {
                    c(d, ref d._EmployeeGroupCourseAssignments, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.EmployeeGroupCourseAssignment> _EmployeeGroupCourseAssignments_GetReferencedEntities(global::LightSwitchApplication.EmployeeGroup.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass>(global::LightSwitchApplication.EmployeeGroup.DetailsClass.PropertySetProperties.EmployeeGroupCourseAssignments, ref d._EmployeeGroupCourseAssignments);
                }
                private static global::System.Collections.IEnumerable _EmployeeGroupCourseAssignments_GetEntityCollection(global::LightSwitchApplication.EmployeeGroup.DetailsClass d)
                {
                    return d.ImplementationEntity.EmployeeGroupCourseAssignments;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string>.Data _EmployeeGroupName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::LightSwitchApplication.Employee>.Data _Employees;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass, global::LightSwitchApplication.EmployeeGroupCourseAssignment>.Data _EmployeeGroupCourseAssignments;
            
        }
    
        #endregion
    }
    
    #endregion
}
