//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region Course
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Course :
        global::LightSwitchApplication.Course.DetailsClass.IImplementation
    {
        partial void OnCourseStatus_CourseChanged()
        {
            this.___OnPropertyChanged("CourseStatus_Course");
            this.___OnPropertyChanged("CourseStatus");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCourseReferenceChanged()
        {
            this.___OnPropertyChanged("CourseReference");
        }
        
        partial void OnCourseTitleChanged()
        {
            this.___OnPropertyChanged("CourseTitle");
        }
        
        partial void OnCourseDescriptionChanged()
        {
            this.___OnPropertyChanged("CourseDescription");
        }
        
        partial void OnCourseVersionChanged()
        {
            this.___OnPropertyChanged("CourseVersion");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Course.DetailsClass.IImplementation.CourseStatus
        {
            get
            {
                return this.CourseStatus;
            }
            set
            {
                this.CourseStatus = (global::LightSwitchApplication.Implementation.CourseStatus)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.CourseStatus> __CourseStatus
        {
            get
            {
                if (this.___CourseStatus == null)
                {
                    this.___CourseStatus = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.CourseStatus>(
                        this,
                        "CourseStatus",
                        new string[] { "CourseStatus_Course" },
                        e => global::System.Object.Equals(e.Id, this.CourseStatus_Course),
                        () => this._CourseStatus,
                        e => this._CourseStatus = e);
                }
                return this.___CourseStatus;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.CourseStatus> ___CourseStatus;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Course.DetailsClass.IImplementation.EmployeeGroupCourseAssignments
        {
            get
            {
                return this.EmployeeGroupCourseAssignments;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeGroupCourseAssignment> __EmployeeGroupCourseAssignments
        {
            get
            {
                if (this.___EmployeeGroupCourseAssignments == null)
                {
                    this.___EmployeeGroupCourseAssignments = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeGroupCourseAssignment>(
                        this,
                        "EmployeeGroupCourseAssignments",
                        () => this._EmployeeGroupCourseAssignments,
                        e => global::System.Object.Equals(e.EmployeeGroupCourseAssignment_Course, this.Id));
                }
                return this.___EmployeeGroupCourseAssignments;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeGroupCourseAssignment> ___EmployeeGroupCourseAssignments;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Course.DetailsClass.IImplementation.EmployeeCourseAssignments
        {
            get
            {
                return this.EmployeeCourseAssignments;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeCourseAssignment> __EmployeeCourseAssignments
        {
            get
            {
                if (this.___EmployeeCourseAssignments == null)
                {
                    this.___EmployeeCourseAssignments = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeCourseAssignment>(
                        this,
                        "EmployeeCourseAssignments",
                        () => this._EmployeeCourseAssignments,
                        e => global::System.Object.Equals(e.EmployeeCourseAssignment_Course, this.Id));
                }
                return this.___EmployeeCourseAssignments;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeCourseAssignment> ___EmployeeCourseAssignments;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Course.DetailsClass.IImplementation.JobRoleCourseAssignments
        {
            get
            {
                return this.JobRoleCourseAssignments;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.JobRoleCourseAssignment> __JobRoleCourseAssignments
        {
            get
            {
                if (this.___JobRoleCourseAssignments == null)
                {
                    this.___JobRoleCourseAssignments = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.JobRoleCourseAssignment>(
                        this,
                        "JobRoleCourseAssignments",
                        () => this._JobRoleCourseAssignments,
                        e => global::System.Object.Equals(e.JobRoleCourseAssignment_Course, this.Id));
                }
                return this.___JobRoleCourseAssignments;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.JobRoleCourseAssignment> ___JobRoleCourseAssignments;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Course.DetailsClass.IImplementation.EmployeeTrainingRecords
        {
            get
            {
                return this.EmployeeTrainingRecords;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeTrainingRecord> __EmployeeTrainingRecords
        {
            get
            {
                if (this.___EmployeeTrainingRecords == null)
                {
                    this.___EmployeeTrainingRecords = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeTrainingRecord>(
                        this,
                        "EmployeeTrainingRecords",
                        () => this._EmployeeTrainingRecords,
                        e => global::System.Object.Equals(e.EmployeeTrainingRecord_Course, this.Id));
                }
                return this.___EmployeeTrainingRecords;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeTrainingRecord> ___EmployeeTrainingRecords;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Course.DetailsClass.IImplementation.TrainingSessions
        {
            get
            {
                return this.TrainingSessions;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TrainingSession> __TrainingSessions
        {
            get
            {
                if (this.___TrainingSessions == null)
                {
                    this.___TrainingSessions = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TrainingSession>(
                        this,
                        "TrainingSessions",
                        () => this._TrainingSessions,
                        e => global::System.Object.Equals(e.TrainingSession_Course, this.Id));
                }
                return this.___TrainingSessions;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TrainingSession> ___TrainingSessions;
        
    }
    #endregion
    
    #region CourseStatus
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class CourseStatus :
        global::LightSwitchApplication.CourseStatus.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.CourseStatus.DetailsClass.IImplementation.Courses
        {
            get
            {
                return this.Courses;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Course> __Courses
        {
            get
            {
                if (this.___Courses == null)
                {
                    this.___Courses = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Course>(
                        this,
                        "Courses",
                        () => this._Courses,
                        e => global::System.Object.Equals(e.CourseStatus_Course, this.Id));
                }
                return this.___Courses;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Course> ___Courses;
        
    }
    #endregion
    
    #region EmployeeCourseAssignment
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeCourseAssignment :
        global::LightSwitchApplication.EmployeeCourseAssignment.DetailsClass.IImplementation
    {
        partial void OnEmployeeCourseAssignment_CourseChanged()
        {
            this.___OnPropertyChanged("EmployeeCourseAssignment_Course");
            this.___OnPropertyChanged("Course");
        }
        
        partial void OnEmployeeCourseAssignment_EmployeeChanged()
        {
            this.___OnPropertyChanged("EmployeeCourseAssignment_Employee");
            this.___OnPropertyChanged("Employee");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnDateAssignedChanged()
        {
            this.___OnPropertyChanged("DateAssigned");
        }
        
        partial void OnTargetCompletionDateChanged()
        {
            this.___OnPropertyChanged("TargetCompletionDate");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeCourseAssignment.DetailsClass.IImplementation.Course
        {
            get
            {
                return this.Course;
            }
            set
            {
                this.Course = (global::LightSwitchApplication.Implementation.Course)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Course> __Course
        {
            get
            {
                if (this.___Course == null)
                {
                    this.___Course = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Course>(
                        this,
                        "Course",
                        new string[] { "EmployeeCourseAssignment_Course" },
                        e => global::System.Object.Equals(e.Id, this.EmployeeCourseAssignment_Course),
                        () => this._Course,
                        e => this._Course = e);
                }
                return this.___Course;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Course> ___Course;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeCourseAssignment.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __Employee
        {
            get
            {
                if (this.___Employee == null)
                {
                    this.___Employee = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "Employee",
                        new string[] { "EmployeeCourseAssignment_Employee" },
                        e => global::System.Object.Equals(e.Id, this.EmployeeCourseAssignment_Employee),
                        () => this._Employee,
                        e => this._Employee = e);
                }
                return this.___Employee;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___Employee;
        
    }
    #endregion
    
    #region EmployeeGroupCourseAssignment
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeGroupCourseAssignment :
        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.IImplementation
    {
        partial void OnEmployeeGroupCourseAssignment_EmployeeGroupChanged()
        {
            this.___OnPropertyChanged("EmployeeGroupCourseAssignment_EmployeeGroup");
            this.___OnPropertyChanged("EmployeeGroup");
        }
        
        partial void OnEmployeeGroupCourseAssignment_CourseChanged()
        {
            this.___OnPropertyChanged("EmployeeGroupCourseAssignment_Course");
            this.___OnPropertyChanged("Course");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnDateAssignedChanged()
        {
            this.___OnPropertyChanged("DateAssigned");
        }
        
        partial void OnTargetCompletionDateChanged()
        {
            this.___OnPropertyChanged("TargetCompletionDate");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.IImplementation.EmployeeGroup
        {
            get
            {
                return this.EmployeeGroup;
            }
            set
            {
                this.EmployeeGroup = (global::LightSwitchApplication.Implementation.EmployeeGroup)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.EmployeeGroup> __EmployeeGroup
        {
            get
            {
                if (this.___EmployeeGroup == null)
                {
                    this.___EmployeeGroup = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.EmployeeGroup>(
                        this,
                        "EmployeeGroup",
                        new string[] { "EmployeeGroupCourseAssignment_EmployeeGroup" },
                        e => global::System.Object.Equals(e.Id, this.EmployeeGroupCourseAssignment_EmployeeGroup),
                        () => this._EmployeeGroup,
                        e => this._EmployeeGroup = e);
                }
                return this.___EmployeeGroup;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.EmployeeGroup> ___EmployeeGroup;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.IImplementation.Course
        {
            get
            {
                return this.Course;
            }
            set
            {
                this.Course = (global::LightSwitchApplication.Implementation.Course)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Course> __Course
        {
            get
            {
                if (this.___Course == null)
                {
                    this.___Course = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Course>(
                        this,
                        "Course",
                        new string[] { "EmployeeGroupCourseAssignment_Course" },
                        e => global::System.Object.Equals(e.Id, this.EmployeeGroupCourseAssignment_Course),
                        () => this._Course,
                        e => this._Course = e);
                }
                return this.___Course;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Course> ___Course;
        
    }
    #endregion
    
    #region EmployeeGroup
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeGroup :
        global::LightSwitchApplication.EmployeeGroup.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnEmployeeGroupNameChanged()
        {
            this.___OnPropertyChanged("EmployeeGroupName");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.EmployeeGroup.DetailsClass.IImplementation.Employees
        {
            get
            {
                return this.Employees;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Employee> __Employees
        {
            get
            {
                if (this.___Employees == null)
                {
                    this.___Employees = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "Employees",
                        () => this._Employees,
                        e => global::System.Object.Equals(e.EmployeeGroup_Employee, this.Id));
                }
                return this.___Employees;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Employee> ___Employees;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.EmployeeGroup.DetailsClass.IImplementation.EmployeeGroupCourseAssignments
        {
            get
            {
                return this.EmployeeGroupCourseAssignments;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeGroupCourseAssignment> __EmployeeGroupCourseAssignments
        {
            get
            {
                if (this.___EmployeeGroupCourseAssignments == null)
                {
                    this.___EmployeeGroupCourseAssignments = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeGroupCourseAssignment>(
                        this,
                        "EmployeeGroupCourseAssignments",
                        () => this._EmployeeGroupCourseAssignments,
                        e => global::System.Object.Equals(e.EmployeeGroupCourseAssignment_EmployeeGroup, this.Id));
                }
                return this.___EmployeeGroupCourseAssignments;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeGroupCourseAssignment> ___EmployeeGroupCourseAssignments;
        
    }
    #endregion
    
    #region EmployeeJobRole
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeJobRole :
        global::LightSwitchApplication.EmployeeJobRole.DetailsClass.IImplementation
    {
        partial void OnEmployeeJobRole_EmployeeChanged()
        {
            this.___OnPropertyChanged("EmployeeJobRole_Employee");
            this.___OnPropertyChanged("Employee");
        }
        
        partial void OnEmployeeJobRole_JobRoleChanged()
        {
            this.___OnPropertyChanged("EmployeeJobRole_JobRole");
            this.___OnPropertyChanged("JobRole");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeJobRole.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __Employee
        {
            get
            {
                if (this.___Employee == null)
                {
                    this.___Employee = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "Employee",
                        new string[] { "EmployeeJobRole_Employee" },
                        e => global::System.Object.Equals(e.Id, this.EmployeeJobRole_Employee),
                        () => this._Employee,
                        e => this._Employee = e);
                }
                return this.___Employee;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___Employee;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeJobRole.DetailsClass.IImplementation.JobRole
        {
            get
            {
                return this.JobRole;
            }
            set
            {
                this.JobRole = (global::LightSwitchApplication.Implementation.JobRole)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.JobRole> __JobRole
        {
            get
            {
                if (this.___JobRole == null)
                {
                    this.___JobRole = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.JobRole>(
                        this,
                        "JobRole",
                        new string[] { "EmployeeJobRole_JobRole" },
                        e => global::System.Object.Equals(e.Id, this.EmployeeJobRole_JobRole),
                        () => this._JobRole,
                        e => this._JobRole = e);
                }
                return this.___JobRole;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.JobRole> ___JobRole;
        
    }
    #endregion
    
    #region Employee
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Employee :
        global::LightSwitchApplication.Employee.DetailsClass.IImplementation
    {
        partial void OnEmployeeGroup_EmployeeChanged()
        {
            this.___OnPropertyChanged("EmployeeGroup_Employee");
            this.___OnPropertyChanged("EmployeeGroup");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnLastNameChanged()
        {
            this.___OnPropertyChanged("LastName");
        }
        
        partial void OnFirstNameChanged()
        {
            this.___OnPropertyChanged("FirstName");
        }
        
        partial void OnUserNameChanged()
        {
            this.___OnPropertyChanged("UserName");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnCurrentChanged()
        {
            this.___OnPropertyChanged("Current");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Employee.DetailsClass.IImplementation.EmployeeGroup
        {
            get
            {
                return this.EmployeeGroup;
            }
            set
            {
                this.EmployeeGroup = (global::LightSwitchApplication.Implementation.EmployeeGroup)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.EmployeeGroup> __EmployeeGroup
        {
            get
            {
                if (this.___EmployeeGroup == null)
                {
                    this.___EmployeeGroup = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.EmployeeGroup>(
                        this,
                        "EmployeeGroup",
                        new string[] { "EmployeeGroup_Employee" },
                        e => global::System.Object.Equals(e.Id, this.EmployeeGroup_Employee),
                        () => this._EmployeeGroup,
                        e => this._EmployeeGroup = e);
                }
                return this.___EmployeeGroup;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.EmployeeGroup> ___EmployeeGroup;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.EmployeeCourseAssignments
        {
            get
            {
                return this.EmployeeCourseAssignments;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeCourseAssignment> __EmployeeCourseAssignments
        {
            get
            {
                if (this.___EmployeeCourseAssignments == null)
                {
                    this.___EmployeeCourseAssignments = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeCourseAssignment>(
                        this,
                        "EmployeeCourseAssignments",
                        () => this._EmployeeCourseAssignments,
                        e => global::System.Object.Equals(e.EmployeeCourseAssignment_Employee, this.Id));
                }
                return this.___EmployeeCourseAssignments;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeCourseAssignment> ___EmployeeCourseAssignments;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.EmployeeJobRoles
        {
            get
            {
                return this.EmployeeJobRoles;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeJobRole> __EmployeeJobRoles
        {
            get
            {
                if (this.___EmployeeJobRoles == null)
                {
                    this.___EmployeeJobRoles = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeJobRole>(
                        this,
                        "EmployeeJobRoles",
                        () => this._EmployeeJobRoles,
                        e => global::System.Object.Equals(e.EmployeeJobRole_Employee, this.Id));
                }
                return this.___EmployeeJobRoles;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeJobRole> ___EmployeeJobRoles;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.EmployeeTrainingRecords
        {
            get
            {
                return this.EmployeeTrainingRecords;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeTrainingRecord> __EmployeeTrainingRecords
        {
            get
            {
                if (this.___EmployeeTrainingRecords == null)
                {
                    this.___EmployeeTrainingRecords = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeTrainingRecord>(
                        this,
                        "EmployeeTrainingRecords",
                        () => this._EmployeeTrainingRecords,
                        e => global::System.Object.Equals(e.EmployeeTrainingRecord_Employee, this.Id));
                }
                return this.___EmployeeTrainingRecords;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeTrainingRecord> ___EmployeeTrainingRecords;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.TrainingSessions
        {
            get
            {
                return this.TrainingSessions;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TrainingSession> __TrainingSessions
        {
            get
            {
                if (this.___TrainingSessions == null)
                {
                    this.___TrainingSessions = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TrainingSession>(
                        this,
                        "TrainingSessions",
                        () => this._TrainingSessions,
                        e => global::System.Object.Equals(e.TrainingSession_Employee, this.Id));
                }
                return this.___TrainingSessions;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TrainingSession> ___TrainingSessions;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.TrainingSessionAttendees
        {
            get
            {
                return this.TrainingSessionAttendees;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TrainingSessionAttendee> __TrainingSessionAttendees
        {
            get
            {
                if (this.___TrainingSessionAttendees == null)
                {
                    this.___TrainingSessionAttendees = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TrainingSessionAttendee>(
                        this,
                        "TrainingSessionAttendees",
                        () => this._TrainingSessionAttendees,
                        e => global::System.Object.Equals(e.TrainingSessionAttendee_Employee, this.Id));
                }
                return this.___TrainingSessionAttendees;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TrainingSessionAttendee> ___TrainingSessionAttendees;
        
    }
    #endregion
    
    #region EmployeeTrainingRecord
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class EmployeeTrainingRecord :
        global::LightSwitchApplication.EmployeeTrainingRecord.DetailsClass.IImplementation
    {
        partial void OnEmployeeTrainingRecord_EmployeeChanged()
        {
            this.___OnPropertyChanged("EmployeeTrainingRecord_Employee");
            this.___OnPropertyChanged("Employee");
        }
        
        partial void OnEmployeeTrainingRecord_CourseChanged()
        {
            this.___OnPropertyChanged("EmployeeTrainingRecord_Course");
            this.___OnPropertyChanged("Course");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnDateAssignedChanged()
        {
            this.___OnPropertyChanged("DateAssigned");
        }
        
        partial void OnTargetCompletionDateChanged()
        {
            this.___OnPropertyChanged("TargetCompletionDate");
        }
        
        partial void OnDateTrainingCommencedChanged()
        {
            this.___OnPropertyChanged("DateTrainingCommenced");
        }
        
        partial void OnDateTrainingCompletedChanged()
        {
            this.___OnPropertyChanged("DateTrainingCompleted");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeTrainingRecord.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __Employee
        {
            get
            {
                if (this.___Employee == null)
                {
                    this.___Employee = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "Employee",
                        new string[] { "EmployeeTrainingRecord_Employee" },
                        e => global::System.Object.Equals(e.Id, this.EmployeeTrainingRecord_Employee),
                        () => this._Employee,
                        e => this._Employee = e);
                }
                return this.___Employee;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___Employee;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.EmployeeTrainingRecord.DetailsClass.IImplementation.Course
        {
            get
            {
                return this.Course;
            }
            set
            {
                this.Course = (global::LightSwitchApplication.Implementation.Course)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Course> __Course
        {
            get
            {
                if (this.___Course == null)
                {
                    this.___Course = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Course>(
                        this,
                        "Course",
                        new string[] { "EmployeeTrainingRecord_Course" },
                        e => global::System.Object.Equals(e.Id, this.EmployeeTrainingRecord_Course),
                        () => this._Course,
                        e => this._Course = e);
                }
                return this.___Course;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Course> ___Course;
        
    }
    #endregion
    
    #region JobRoleCourseAssignment
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class JobRoleCourseAssignment :
        global::LightSwitchApplication.JobRoleCourseAssignment.DetailsClass.IImplementation
    {
        partial void OnJobRoleCourseAssignment_JobRoleChanged()
        {
            this.___OnPropertyChanged("JobRoleCourseAssignment_JobRole");
            this.___OnPropertyChanged("JobRole");
        }
        
        partial void OnJobRoleCourseAssignment_CourseChanged()
        {
            this.___OnPropertyChanged("JobRoleCourseAssignment_Course");
            this.___OnPropertyChanged("Course");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnDateAssignedChanged()
        {
            this.___OnPropertyChanged("DateAssigned");
        }
        
        partial void OnTargetCompletionDateChanged()
        {
            this.___OnPropertyChanged("TargetCompletionDate");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.JobRoleCourseAssignment.DetailsClass.IImplementation.JobRole
        {
            get
            {
                return this.JobRole;
            }
            set
            {
                this.JobRole = (global::LightSwitchApplication.Implementation.JobRole)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.JobRole> __JobRole
        {
            get
            {
                if (this.___JobRole == null)
                {
                    this.___JobRole = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.JobRole>(
                        this,
                        "JobRole",
                        new string[] { "JobRoleCourseAssignment_JobRole" },
                        e => global::System.Object.Equals(e.Id, this.JobRoleCourseAssignment_JobRole),
                        () => this._JobRole,
                        e => this._JobRole = e);
                }
                return this.___JobRole;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.JobRole> ___JobRole;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.JobRoleCourseAssignment.DetailsClass.IImplementation.Course
        {
            get
            {
                return this.Course;
            }
            set
            {
                this.Course = (global::LightSwitchApplication.Implementation.Course)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Course> __Course
        {
            get
            {
                if (this.___Course == null)
                {
                    this.___Course = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Course>(
                        this,
                        "Course",
                        new string[] { "JobRoleCourseAssignment_Course" },
                        e => global::System.Object.Equals(e.Id, this.JobRoleCourseAssignment_Course),
                        () => this._Course,
                        e => this._Course = e);
                }
                return this.___Course;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Course> ___Course;
        
    }
    #endregion
    
    #region JobRole
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class JobRole :
        global::LightSwitchApplication.JobRole.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnJobRoleDescriptionChanged()
        {
            this.___OnPropertyChanged("JobRoleDescription");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.JobRole.DetailsClass.IImplementation.EmployeeJobRoles
        {
            get
            {
                return this.EmployeeJobRoles;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeJobRole> __EmployeeJobRoles
        {
            get
            {
                if (this.___EmployeeJobRoles == null)
                {
                    this.___EmployeeJobRoles = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeJobRole>(
                        this,
                        "EmployeeJobRoles",
                        () => this._EmployeeJobRoles,
                        e => global::System.Object.Equals(e.EmployeeJobRole_JobRole, this.Id));
                }
                return this.___EmployeeJobRoles;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.EmployeeJobRole> ___EmployeeJobRoles;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.JobRole.DetailsClass.IImplementation.JobRoleCourseAssignments
        {
            get
            {
                return this.JobRoleCourseAssignments;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.JobRoleCourseAssignment> __JobRoleCourseAssignments
        {
            get
            {
                if (this.___JobRoleCourseAssignments == null)
                {
                    this.___JobRoleCourseAssignments = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.JobRoleCourseAssignment>(
                        this,
                        "JobRoleCourseAssignments",
                        () => this._JobRoleCourseAssignments,
                        e => global::System.Object.Equals(e.JobRoleCourseAssignment_JobRole, this.Id));
                }
                return this.___JobRoleCourseAssignments;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.JobRoleCourseAssignment> ___JobRoleCourseAssignments;
        
    }
    #endregion
    
    #region TrainingSessionAttendee
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TrainingSessionAttendee :
        global::LightSwitchApplication.TrainingSessionAttendee.DetailsClass.IImplementation
    {
        partial void OnTrainingSessionAttendee_EmployeeChanged()
        {
            this.___OnPropertyChanged("TrainingSessionAttendee_Employee");
            this.___OnPropertyChanged("Employee");
        }
        
        partial void OnTrainingSessionAttendee_TrainingSessionChanged()
        {
            this.___OnPropertyChanged("TrainingSessionAttendee_TrainingSession");
            this.___OnPropertyChanged("TrainingSession");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TrainingSessionAttendee.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __Employee
        {
            get
            {
                if (this.___Employee == null)
                {
                    this.___Employee = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "Employee",
                        new string[] { "TrainingSessionAttendee_Employee" },
                        e => global::System.Object.Equals(e.Id, this.TrainingSessionAttendee_Employee),
                        () => this._Employee,
                        e => this._Employee = e);
                }
                return this.___Employee;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___Employee;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TrainingSessionAttendee.DetailsClass.IImplementation.TrainingSession
        {
            get
            {
                return this.TrainingSession;
            }
            set
            {
                this.TrainingSession = (global::LightSwitchApplication.Implementation.TrainingSession)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.TrainingSession> __TrainingSession
        {
            get
            {
                if (this.___TrainingSession == null)
                {
                    this.___TrainingSession = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.TrainingSession>(
                        this,
                        "TrainingSession",
                        new string[] { "TrainingSessionAttendee_TrainingSession" },
                        e => global::System.Object.Equals(e.Id, this.TrainingSessionAttendee_TrainingSession),
                        () => this._TrainingSession,
                        e => this._TrainingSession = e);
                }
                return this.___TrainingSession;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.TrainingSession> ___TrainingSession;
        
    }
    #endregion
    
    #region TrainingSession
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TrainingSession :
        global::LightSwitchApplication.TrainingSession.DetailsClass.IImplementation
    {
        partial void OnTrainingSession_EmployeeChanged()
        {
            this.___OnPropertyChanged("TrainingSession_Employee");
            this.___OnPropertyChanged("Employee");
        }
        
        partial void OnTrainingSession_CourseChanged()
        {
            this.___OnPropertyChanged("TrainingSession_Course");
            this.___OnPropertyChanged("Course");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnStartDateChanged()
        {
            this.___OnPropertyChanged("StartDate");
        }
        
        partial void OnEndDateChanged()
        {
            this.___OnPropertyChanged("EndDate");
        }
        
        partial void OnMaximumAttendeesChanged()
        {
            this.___OnPropertyChanged("MaximumAttendees");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TrainingSession.DetailsClass.IImplementation.Employee
        {
            get
            {
                return this.Employee;
            }
            set
            {
                this.Employee = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __Employee
        {
            get
            {
                if (this.___Employee == null)
                {
                    this.___Employee = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "Employee",
                        new string[] { "TrainingSession_Employee" },
                        e => global::System.Object.Equals(e.Id, this.TrainingSession_Employee),
                        () => this._Employee,
                        e => this._Employee = e);
                }
                return this.___Employee;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___Employee;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TrainingSession.DetailsClass.IImplementation.Course
        {
            get
            {
                return this.Course;
            }
            set
            {
                this.Course = (global::LightSwitchApplication.Implementation.Course)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Course> __Course
        {
            get
            {
                if (this.___Course == null)
                {
                    this.___Course = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Course>(
                        this,
                        "Course",
                        new string[] { "TrainingSession_Course" },
                        e => global::System.Object.Equals(e.Id, this.TrainingSession_Course),
                        () => this._Course,
                        e => this._Course = e);
                }
                return this.___Course;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Course> ___Course;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.TrainingSession.DetailsClass.IImplementation.TrainingSessionAttendees
        {
            get
            {
                return this.TrainingSessionAttendees;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TrainingSessionAttendee> __TrainingSessionAttendees
        {
            get
            {
                if (this.___TrainingSessionAttendees == null)
                {
                    this.___TrainingSessionAttendees = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TrainingSessionAttendee>(
                        this,
                        "TrainingSessionAttendees",
                        () => this._TrainingSessionAttendees,
                        e => global::System.Object.Equals(e.TrainingSessionAttendee_TrainingSession, this.Id));
                }
                return this.___TrainingSessionAttendees;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.TrainingSessionAttendee> ___TrainingSessionAttendees;
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Course))
            {
                return new global::LightSwitchApplication.Implementation.Course();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.CourseStatus))
            {
                return new global::LightSwitchApplication.Implementation.CourseStatus();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeCourseAssignment))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeCourseAssignment();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeGroupCourseAssignment))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeGroupCourseAssignment();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeGroup))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeGroup();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeJobRole))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeJobRole();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.EmployeeTrainingRecord))
            {
                return new global::LightSwitchApplication.Implementation.EmployeeTrainingRecord();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.JobRoleCourseAssignment))
            {
                return new global::LightSwitchApplication.Implementation.JobRoleCourseAssignment();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.JobRole))
            {
                return new global::LightSwitchApplication.Implementation.JobRole();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TrainingSessionAttendee))
            {
                return new global::LightSwitchApplication.Implementation.TrainingSessionAttendee();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TrainingSession))
            {
                return new global::LightSwitchApplication.Implementation.TrainingSession();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Course) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Course);
            }
            if (typeof(global::LightSwitchApplication.CourseStatus) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.CourseStatus);
            }
            if (typeof(global::LightSwitchApplication.EmployeeCourseAssignment) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeCourseAssignment);
            }
            if (typeof(global::LightSwitchApplication.EmployeeGroupCourseAssignment) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeGroupCourseAssignment);
            }
            if (typeof(global::LightSwitchApplication.EmployeeGroup) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeGroup);
            }
            if (typeof(global::LightSwitchApplication.EmployeeJobRole) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeJobRole);
            }
            if (typeof(global::LightSwitchApplication.Employee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Employee);
            }
            if (typeof(global::LightSwitchApplication.EmployeeTrainingRecord) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.EmployeeTrainingRecord);
            }
            if (typeof(global::LightSwitchApplication.JobRoleCourseAssignment) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.JobRoleCourseAssignment);
            }
            if (typeof(global::LightSwitchApplication.JobRole) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.JobRole);
            }
            if (typeof(global::LightSwitchApplication.TrainingSessionAttendee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TrainingSessionAttendee);
            }
            if (typeof(global::LightSwitchApplication.TrainingSession) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TrainingSession);
            }
            return null;
        }
    }
}
