

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class EmployeeGroupCourseAssignment : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the EmployeeGroupCourseAssignment entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EmployeeGroupCourseAssignment()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EmployeeGroupCourseAssignment(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EmployeeGroupCourseAssignment> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmployeeGroupCourseAssignment_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmployeeGroupCourseAssignment_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.SetValue(this, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DateAssigned
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.DateAssigned);
            }
            set
            {
                global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.SetValue(this, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.DateAssigned, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateAssigned_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateAssigned_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateAssigned_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime TargetCompletionDate
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.TargetCompletionDate);
            }
            set
            {
                global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.SetValue(this, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.TargetCompletionDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetCompletionDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetCompletionDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetCompletionDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.SetValue(this, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.EmployeeGroup EmployeeGroup
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.EmployeeGroup);
            }
            set
            {
                global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.SetValue(this, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.EmployeeGroup, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmployeeGroup_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmployeeGroup_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmployeeGroup_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Course Course
        {
            get
            {
                return global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.GetValue(this, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.Course);
            }
            set
            {
                global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.SetValue(this, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.Course, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Course_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Course_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Course_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.EmployeeGroupCourseAssignment,
                global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass,
                global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.IImplementation,
                global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass>.Entry
                __EmployeeGroupCourseAssignmentEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass>.Entry(
                    global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.__EmployeeGroupCourseAssignment_CreateNew,
                    global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.__EmployeeGroupCourseAssignment_Created,
                    global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.__EmployeeGroupCourseAssignment_AllowSaveWithErrors);
            private static global::LightSwitchApplication.EmployeeGroupCourseAssignment __EmployeeGroupCourseAssignment_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EmployeeGroupCourseAssignment> es)
            {
                return new global::LightSwitchApplication.EmployeeGroupCourseAssignment(es);
            }
            private static void __EmployeeGroupCourseAssignment_Created(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
            {
                e.EmployeeGroupCourseAssignment_Created();
            }
            private static bool __EmployeeGroupCourseAssignment_AllowSaveWithErrors(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
            {
                bool result = false;
                e.EmployeeGroupCourseAssignment_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.DateTime> DateAssigned
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.DateAssigned) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.DateTime> TargetCompletionDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.TargetCompletionDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::LightSwitchApplication.EmployeeGroup> EmployeeGroup
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.EmployeeGroup) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::LightSwitchApplication.EmployeeGroup>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::LightSwitchApplication.Course> Course
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.Course) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::LightSwitchApplication.Course>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new global::System.DateTime DateAssigned { get; set; }
                new global::System.DateTime TargetCompletionDate { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation EmployeeGroup { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Course { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, int>.Data> c, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.EmployeeGroupCourseAssignment e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.DateTime>.Entry
                    DateAssigned = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.DateTime>.Entry(
                        "DateAssigned",
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._DateAssigned_Stub,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._DateAssigned_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._DateAssigned_Validate,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._DateAssigned_GetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._DateAssigned_SetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._DateAssigned_OnValueChanged);
                private static void _DateAssigned_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d, object sf)
                {
                    c(d, ref d._DateAssigned, sf);
                }
                private static bool _DateAssigned_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    bool result = false;
                    e.DateAssigned_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateAssigned_Validate(global::LightSwitchApplication.EmployeeGroupCourseAssignment e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateAssigned_Validate(r);
                }
                private static global::System.DateTime _DateAssigned_GetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d)
                {
                    return d.ImplementationEntity.DateAssigned;
                }
                private static void _DateAssigned_SetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.DateAssigned = global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.TruncateDate(v);
                }
                private static void _DateAssigned_OnValueChanged(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    e.DateAssigned_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.DateTime>.Entry
                    TargetCompletionDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.DateTime>.Entry(
                        "TargetCompletionDate",
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._TargetCompletionDate_Stub,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._TargetCompletionDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._TargetCompletionDate_Validate,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._TargetCompletionDate_GetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._TargetCompletionDate_SetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._TargetCompletionDate_OnValueChanged);
                private static void _TargetCompletionDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d, object sf)
                {
                    c(d, ref d._TargetCompletionDate, sf);
                }
                private static bool _TargetCompletionDate_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    bool result = false;
                    e.TargetCompletionDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _TargetCompletionDate_Validate(global::LightSwitchApplication.EmployeeGroupCourseAssignment e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TargetCompletionDate_Validate(r);
                }
                private static global::System.DateTime _TargetCompletionDate_GetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d)
                {
                    return d.ImplementationEntity.TargetCompletionDate;
                }
                private static void _TargetCompletionDate_SetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.TargetCompletionDate = global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.TruncateDate(v);
                }
                private static void _TargetCompletionDate_OnValueChanged(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    e.TargetCompletionDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, string>.Data> c, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.EmployeeGroupCourseAssignment e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.EmployeeGroupCourseAssignment e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, string>.Data> c, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.EmployeeGroupCourseAssignment e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.EmployeeGroupCourseAssignment e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.EmployeeGroupCourseAssignment e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::LightSwitchApplication.EmployeeGroup>.Entry
                    EmployeeGroup = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::LightSwitchApplication.EmployeeGroup>.Entry(
                        "EmployeeGroup",
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._EmployeeGroup_Stub,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._EmployeeGroup_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._EmployeeGroup_Validate,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._EmployeeGroup_GetCoreImplementationValue,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._EmployeeGroup_GetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._EmployeeGroup_SetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._EmployeeGroup_Refresh,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._EmployeeGroup_OnValueChanged);
                private static void _EmployeeGroup_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::LightSwitchApplication.EmployeeGroup>.Data> c, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d, object sf)
                {
                    c(d, ref d._EmployeeGroup, sf);
                }
                private static bool _EmployeeGroup_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    bool result = false;
                    e.EmployeeGroup_IsReadOnly(ref result);
                    return result;
                }
                private static void _EmployeeGroup_Validate(global::LightSwitchApplication.EmployeeGroupCourseAssignment e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EmployeeGroup_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _EmployeeGroup_GetCoreImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d)
                {
                    return d.ImplementationEntity.EmployeeGroup;
                }
                private static global::LightSwitchApplication.EmployeeGroup _EmployeeGroup_GetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.EmployeeGroup, global::LightSwitchApplication.EmployeeGroup.DetailsClass>(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.EmployeeGroup, ref d._EmployeeGroup);
                }
                private static void _EmployeeGroup_SetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d, global::LightSwitchApplication.EmployeeGroup v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.EmployeeGroup, ref d._EmployeeGroup, (i, ev) => i.EmployeeGroup = ev, v);
                }
                private static void _EmployeeGroup_Refresh(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.EmployeeGroup, ref d._EmployeeGroup);
                }
                private static void _EmployeeGroup_OnValueChanged(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    e.EmployeeGroup_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::LightSwitchApplication.Course>.Entry
                    Course = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::LightSwitchApplication.Course>.Entry(
                        "Course",
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Course_Stub,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Course_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Course_Validate,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Course_GetCoreImplementationValue,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Course_GetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Course_SetImplementationValue,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Course_Refresh,
                        global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties._Course_OnValueChanged);
                private static void _Course_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::LightSwitchApplication.Course>.Data> c, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d, object sf)
                {
                    c(d, ref d._Course, sf);
                }
                private static bool _Course_ComputeIsReadOnly(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    bool result = false;
                    e.Course_IsReadOnly(ref result);
                    return result;
                }
                private static void _Course_Validate(global::LightSwitchApplication.EmployeeGroupCourseAssignment e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Course_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Course_GetCoreImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d)
                {
                    return d.ImplementationEntity.Course;
                }
                private static global::LightSwitchApplication.Course _Course_GetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.Course, ref d._Course);
                }
                private static void _Course_SetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d, global::LightSwitchApplication.Course v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.Course, ref d._Course, (i, ev) => i.Course = ev, v);
                }
                private static void _Course_Refresh(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass.PropertySetProperties.Course, ref d._Course);
                }
                private static void _Course_OnValueChanged(global::LightSwitchApplication.EmployeeGroupCourseAssignment e)
                {
                    e.Course_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.DateTime>.Data _DateAssigned;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.DateTime>.Data _TargetCompletionDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::LightSwitchApplication.EmployeeGroup>.Data _EmployeeGroup;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass, global::LightSwitchApplication.Course>.Data _Course;
            
        }
    
        #endregion
    }
    
    #endregion
}
