

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class Course : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Course entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Course()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Course(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Course> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Course.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Course_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Course_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CourseReference
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseReference);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseReference, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseReference_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseReference_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseReference_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CourseTitle
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseTitle);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseTitle, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseTitle_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseTitle_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseTitle_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CourseDescription
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseDescription);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseDescription, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseDescription_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseDescription_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseDescription_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> CourseVersion
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseVersion);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.CourseStatus CourseStatus
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseStatus);
            }
            set
            {
                global::LightSwitchApplication.Course.DetailsClass.SetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseStatus, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseStatus_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseStatus_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseStatus_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.EmployeeGroupCourseAssignment> EmployeeGroupCourseAssignments
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.EmployeeGroupCourseAssignments);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.EmployeeGroupCourseAssignment> EmployeeGroupCourseAssignmentsQuery
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetQuery(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.EmployeeGroupCourseAssignments);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.EmployeeCourseAssignment> EmployeeCourseAssignments
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.EmployeeCourseAssignments);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.EmployeeCourseAssignment> EmployeeCourseAssignmentsQuery
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetQuery(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.EmployeeCourseAssignments);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.JobRoleCourseAssignment> JobRoleCourseAssignments
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.JobRoleCourseAssignments);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.JobRoleCourseAssignment> JobRoleCourseAssignmentsQuery
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetQuery(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.JobRoleCourseAssignments);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.EmployeeTrainingRecord> EmployeeTrainingRecords
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.EmployeeTrainingRecords);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.EmployeeTrainingRecord> EmployeeTrainingRecordsQuery
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetQuery(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.EmployeeTrainingRecords);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.TrainingSession> TrainingSessions
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetValue(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.TrainingSessions);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.TrainingSession> TrainingSessionsQuery
        {
            get
            {
                return global::LightSwitchApplication.Course.DetailsClass.GetQuery(this, global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.TrainingSessions);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Course,
                global::LightSwitchApplication.Course.DetailsClass,
                global::LightSwitchApplication.Course.DetailsClass.IImplementation,
                global::LightSwitchApplication.Course.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>.Entry
                __CourseEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>.Entry(
                    global::LightSwitchApplication.Course.DetailsClass.__Course_CreateNew,
                    global::LightSwitchApplication.Course.DetailsClass.__Course_Created,
                    global::LightSwitchApplication.Course.DetailsClass.__Course_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Course __Course_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Course> es)
            {
                return new global::LightSwitchApplication.Course(es);
            }
            private static void __Course_Created(global::LightSwitchApplication.Course e)
            {
                e.Course_Created();
            }
            private static bool __Course_AllowSaveWithErrors(global::LightSwitchApplication.Course e)
            {
                bool result = false;
                e.Course_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Course.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string> CourseReference
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseReference) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string> CourseTitle
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseTitle) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string> CourseDescription
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseDescription) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>> CourseVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseStatus> CourseStatus
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseStatus) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseStatus>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeGroupCourseAssignment> EmployeeGroupCourseAssignments
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.EmployeeGroupCourseAssignments) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeGroupCourseAssignment>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeCourseAssignment> EmployeeCourseAssignments
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.EmployeeCourseAssignments) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeCourseAssignment>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.JobRoleCourseAssignment> JobRoleCourseAssignments
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.JobRoleCourseAssignments) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.JobRoleCourseAssignment>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeTrainingRecord> EmployeeTrainingRecords
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.EmployeeTrainingRecords) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeTrainingRecord>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.TrainingSession> TrainingSessions
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.TrainingSessions) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.TrainingSession>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string CourseReference { get; set; }
                new string CourseTitle { get; set; }
                new string CourseDescription { get; set; }
                new global::System.Nullable<int> CourseVersion { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation CourseStatus { get; set; }
                new global::System.Collections.IEnumerable EmployeeGroupCourseAssignments { get; }
                new global::System.Collections.IEnumerable EmployeeCourseAssignments { get; }
                new global::System.Collections.IEnumerable JobRoleCourseAssignments { get; }
                new global::System.Collections.IEnumerable EmployeeTrainingRecords { get; }
                new global::System.Collections.IEnumerable TrainingSessions { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry
                    CourseReference = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry(
                        "CourseReference",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseReference_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseReference_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseReference_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseReference_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseReference_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseReference_OnValueChanged);
                private static void _CourseReference_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._CourseReference, sf);
                }
                private static bool _CourseReference_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.CourseReference_IsReadOnly(ref result);
                    return result;
                }
                private static void _CourseReference_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CourseReference_Validate(r);
                }
                private static string _CourseReference_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.CourseReference;
                }
                private static void _CourseReference_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CourseReference = v;
                }
                private static void _CourseReference_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.CourseReference_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry
                    CourseTitle = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry(
                        "CourseTitle",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseTitle_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseTitle_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseTitle_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseTitle_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseTitle_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseTitle_OnValueChanged);
                private static void _CourseTitle_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._CourseTitle, sf);
                }
                private static bool _CourseTitle_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.CourseTitle_IsReadOnly(ref result);
                    return result;
                }
                private static void _CourseTitle_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CourseTitle_Validate(r);
                }
                private static string _CourseTitle_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.CourseTitle;
                }
                private static void _CourseTitle_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CourseTitle = v;
                }
                private static void _CourseTitle_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.CourseTitle_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry
                    CourseDescription = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry(
                        "CourseDescription",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseDescription_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseDescription_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseDescription_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseDescription_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseDescription_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseDescription_OnValueChanged);
                private static void _CourseDescription_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._CourseDescription, sf);
                }
                private static bool _CourseDescription_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.CourseDescription_IsReadOnly(ref result);
                    return result;
                }
                private static void _CourseDescription_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CourseDescription_Validate(r);
                }
                private static string _CourseDescription_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.CourseDescription;
                }
                private static void _CourseDescription_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CourseDescription = v;
                }
                private static void _CourseDescription_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.CourseDescription_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>>.Entry
                    CourseVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>>.Entry(
                        "CourseVersion",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseVersion_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseVersion_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseVersion_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseVersion_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseVersion_OnValueChanged);
                private static void _CourseVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._CourseVersion, sf);
                }
                private static bool _CourseVersion_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.CourseVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _CourseVersion_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CourseVersion_Validate(r);
                }
                private static global::System.Nullable<int> _CourseVersion_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.CourseVersion;
                }
                private static void _CourseVersion_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.CourseVersion = v;
                }
                private static void _CourseVersion_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.CourseVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseStatus>.Entry
                    CourseStatus = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseStatus>.Entry(
                        "CourseStatus",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseStatus_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseStatus_ComputeIsReadOnly,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseStatus_Validate,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseStatus_GetCoreImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseStatus_GetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseStatus_SetImplementationValue,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseStatus_Refresh,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._CourseStatus_OnValueChanged);
                private static void _CourseStatus_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseStatus>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._CourseStatus, sf);
                }
                private static bool _CourseStatus_ComputeIsReadOnly(global::LightSwitchApplication.Course e)
                {
                    bool result = false;
                    e.CourseStatus_IsReadOnly(ref result);
                    return result;
                }
                private static void _CourseStatus_Validate(global::LightSwitchApplication.Course e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CourseStatus_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _CourseStatus_GetCoreImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.CourseStatus;
                }
                private static global::LightSwitchApplication.CourseStatus _CourseStatus_GetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.CourseStatus, global::LightSwitchApplication.CourseStatus.DetailsClass>(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseStatus, ref d._CourseStatus);
                }
                private static void _CourseStatus_SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass d, global::LightSwitchApplication.CourseStatus v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseStatus, ref d._CourseStatus, (i, ev) => i.CourseStatus = ev, v);
                }
                private static void _CourseStatus_Refresh(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.CourseStatus, ref d._CourseStatus);
                }
                private static void _CourseStatus_OnValueChanged(global::LightSwitchApplication.Course e)
                {
                    e.CourseStatus_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeGroupCourseAssignment>.Entry
                    EmployeeGroupCourseAssignments = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeGroupCourseAssignment>.Entry(
                        "EmployeeGroupCourseAssignments",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._EmployeeGroupCourseAssignments_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._EmployeeGroupCourseAssignments_GetReferencedEntities,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._EmployeeGroupCourseAssignments_GetEntityCollection);
                private static void _EmployeeGroupCourseAssignments_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeGroupCourseAssignment>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._EmployeeGroupCourseAssignments, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.EmployeeGroupCourseAssignment> _EmployeeGroupCourseAssignments_GetReferencedEntities(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.EmployeeGroupCourseAssignment, global::LightSwitchApplication.EmployeeGroupCourseAssignment.DetailsClass>(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.EmployeeGroupCourseAssignments, ref d._EmployeeGroupCourseAssignments);
                }
                private static global::System.Collections.IEnumerable _EmployeeGroupCourseAssignments_GetEntityCollection(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.EmployeeGroupCourseAssignments;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeCourseAssignment>.Entry
                    EmployeeCourseAssignments = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeCourseAssignment>.Entry(
                        "EmployeeCourseAssignments",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._EmployeeCourseAssignments_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._EmployeeCourseAssignments_GetReferencedEntities,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._EmployeeCourseAssignments_GetEntityCollection);
                private static void _EmployeeCourseAssignments_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeCourseAssignment>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._EmployeeCourseAssignments, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.EmployeeCourseAssignment> _EmployeeCourseAssignments_GetReferencedEntities(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.EmployeeCourseAssignment, global::LightSwitchApplication.EmployeeCourseAssignment.DetailsClass>(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.EmployeeCourseAssignments, ref d._EmployeeCourseAssignments);
                }
                private static global::System.Collections.IEnumerable _EmployeeCourseAssignments_GetEntityCollection(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.EmployeeCourseAssignments;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.JobRoleCourseAssignment>.Entry
                    JobRoleCourseAssignments = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.JobRoleCourseAssignment>.Entry(
                        "JobRoleCourseAssignments",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._JobRoleCourseAssignments_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._JobRoleCourseAssignments_GetReferencedEntities,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._JobRoleCourseAssignments_GetEntityCollection);
                private static void _JobRoleCourseAssignments_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.JobRoleCourseAssignment>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._JobRoleCourseAssignments, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.JobRoleCourseAssignment> _JobRoleCourseAssignments_GetReferencedEntities(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.JobRoleCourseAssignment, global::LightSwitchApplication.JobRoleCourseAssignment.DetailsClass>(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.JobRoleCourseAssignments, ref d._JobRoleCourseAssignments);
                }
                private static global::System.Collections.IEnumerable _JobRoleCourseAssignments_GetEntityCollection(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.JobRoleCourseAssignments;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeTrainingRecord>.Entry
                    EmployeeTrainingRecords = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeTrainingRecord>.Entry(
                        "EmployeeTrainingRecords",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._EmployeeTrainingRecords_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._EmployeeTrainingRecords_GetReferencedEntities,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._EmployeeTrainingRecords_GetEntityCollection);
                private static void _EmployeeTrainingRecords_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeTrainingRecord>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._EmployeeTrainingRecords, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.EmployeeTrainingRecord> _EmployeeTrainingRecords_GetReferencedEntities(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.EmployeeTrainingRecord, global::LightSwitchApplication.EmployeeTrainingRecord.DetailsClass>(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.EmployeeTrainingRecords, ref d._EmployeeTrainingRecords);
                }
                private static global::System.Collections.IEnumerable _EmployeeTrainingRecords_GetEntityCollection(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.EmployeeTrainingRecords;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.TrainingSession>.Entry
                    TrainingSessions = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.TrainingSession>.Entry(
                        "TrainingSessions",
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._TrainingSessions_Stub,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._TrainingSessions_GetReferencedEntities,
                        global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties._TrainingSessions_GetEntityCollection);
                private static void _TrainingSessions_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Course.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.TrainingSession>.Data> c, global::LightSwitchApplication.Course.DetailsClass d, object sf)
                {
                    c(d, ref d._TrainingSessions, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.TrainingSession> _TrainingSessions_GetReferencedEntities(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.TrainingSession, global::LightSwitchApplication.TrainingSession.DetailsClass>(global::LightSwitchApplication.Course.DetailsClass.PropertySetProperties.TrainingSessions, ref d._TrainingSessions);
                }
                private static global::System.Collections.IEnumerable _TrainingSessions_GetEntityCollection(global::LightSwitchApplication.Course.DetailsClass d)
                {
                    return d.ImplementationEntity.TrainingSessions;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data _CourseReference;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data _CourseTitle;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data _CourseDescription;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<int>>.Data _CourseVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.CourseStatus>.Data _CourseStatus;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeGroupCourseAssignment>.Data _EmployeeGroupCourseAssignments;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeCourseAssignment>.Data _EmployeeCourseAssignments;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.JobRoleCourseAssignment>.Data _JobRoleCourseAssignments;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.EmployeeTrainingRecord>.Data _EmployeeTrainingRecords;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass, global::LightSwitchApplication.TrainingSession>.Data _TrainingSessions;
            
        }
    
        #endregion
    }
    
    #endregion
}
